source "https://rubygems.org"

ruby file: ".ruby-version"

gem "kirei", git: "https://github.com/swiknaba/kirei.git", branch: "main"
gem "rake", "< 14.0"
gem "falcon", ">= 0.57", "< 0.58"
gem "async-http", ">= 0.105", "< 0.106"
gem "async-websocket", ">= 0.30", "< 0.31"

group :test do
  gem "rspec", "< 4.0"
  gem "rack-test", "< 3.0"
end

group :development do
  gem "sorbet", ">= 0.6", "< 0.7"
  gem "spoom", "< 2.0"
  gem "tapioca", ">= 0.20", "< 0.21"
  gem "rubocop", "< 2.0"
end
