source "https://rubygems.org"

ruby file: ".ruby-version"
gem "kirei", "0.10.0"
gem "rake", "13.4.2"
gem "falcon", "0.57.0"
gem "async-http", "0.105.0"
gem "async-websocket", "0.30.1"

group :test do
  gem "rspec", "3.13.2"
  gem "rack-test", "2.2.0"
end

group :development do
  gem "sorbet", "0.6.13517"
  gem "spoom", "1.8.10"
  gem "tapioca", "0.20.0"
  gem "rubocop", "1.91.0"
end
