# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `async-websocket` gem.
# Please instead update this file by running `bin/tapioca gem async-websocket`.


# Released under the MIT License.
# Copyright, 2018-2024, by Samuel Williams.
#
# pkg:gem/async-websocket#lib/async/websocket/version.rb:6
module Async; end

# pkg:gem/async-websocket#lib/async/websocket/version.rb:7
module Async::WebSocket; end

# This is a basic synchronous websocket client:
#
# pkg:gem/async-websocket#lib/async/websocket/client.rb:23
class Async::WebSocket::Client < ::Protocol::HTTP::Middleware
  include ::Protocol::WebSocket::Headers

  # pkg:gem/async-websocket#lib/async/websocket/client.rb:72
  def initialize(client, **options); end

  # pkg:gem/async-websocket#lib/async/websocket/client.rb:98
  def connect(authority, path, scheme: T.unsafe(nil), headers: T.unsafe(nil), handler: T.unsafe(nil), extensions: T.unsafe(nil), **options, &block); end

  class << self
    # @return [Connection] an open websocket connection to the given endpoint.
    #
    # pkg:gem/async-websocket#lib/async/websocket/client.rb:56
    def connect(endpoint, *arguments, **options, &block); end

    # @return [Client] a client which can be used to establish websocket connections to the given endpoint.
    #
    # pkg:gem/async-websocket#lib/async/websocket/client.rb:27
    def open(endpoint, **options, &block); end
  end
end

# pkg:gem/async-websocket#lib/async/websocket/client.rb:39
class Async::WebSocket::Client::ClientCloseDecorator < ::SimpleDelegator
  # pkg:gem/async-websocket#lib/async/websocket/client.rb:40
  def initialize(client, connection); end

  # pkg:gem/async-websocket#lib/async/websocket/client.rb:45
  def close(*, **, &); end
end

# pkg:gem/async-websocket#lib/async/websocket/client.rb:78
class Async::WebSocket::Client::Framer < ::Protocol::WebSocket::Framer
  # pkg:gem/async-websocket#lib/async/websocket/client.rb:79
  def initialize(pool, connection, stream); end

  # pkg:gem/async-websocket#lib/async/websocket/client.rb:87
  def close; end

  # pkg:gem/async-websocket#lib/async/websocket/client.rb:85
  def connection; end
end

# This is required for HTTP/2 to establish a connection using the WebSocket protocol.
# See https://tools.ietf.org/html/rfc8441 for more details.
#
# pkg:gem/async-websocket#lib/async/websocket/connect_request.rb:18
class Async::WebSocket::ConnectRequest < ::Protocol::HTTP::Request
  include ::Protocol::WebSocket::Headers

  # pkg:gem/async-websocket#lib/async/websocket/connect_request.rb:70
  def initialize(request, protocols: T.unsafe(nil), version: T.unsafe(nil), &block); end

  # pkg:gem/async-websocket#lib/async/websocket/connect_request.rb:84
  def call(connection); end
end

# pkg:gem/async-websocket#lib/async/websocket/connect_request.rb:51
class Async::WebSocket::ConnectRequest::Hijack < ::Protocol::HTTP::Body::Readable
  # pkg:gem/async-websocket#lib/async/websocket/connect_request.rb:52
  def initialize(request); end

  # pkg:gem/async-websocket#lib/async/websocket/connect_request.rb:65
  def call(stream); end

  # pkg:gem/async-websocket#lib/async/websocket/connect_request.rb:61
  def stream; end

  # pkg:gem/async-websocket#lib/async/websocket/connect_request.rb:57
  def stream?; end
end

# pkg:gem/async-websocket#lib/async/websocket/connect_request.rb:21
class Async::WebSocket::ConnectRequest::Wrapper
  # pkg:gem/async-websocket#lib/async/websocket/connect_request.rb:22
  def initialize(stream, response); end

  # pkg:gem/async-websocket#lib/async/websocket/connect_request.rb:27
  def close; end

  # pkg:gem/async-websocket#lib/async/websocket/connect_request.rb:46
  def headers; end

  # pkg:gem/async-websocket#lib/async/websocket/connect_request.rb:35
  def response; end

  # pkg:gem/async-websocket#lib/async/websocket/connect_request.rb:35
  def response=(_arg0); end

  # pkg:gem/async-websocket#lib/async/websocket/connect_request.rb:42
  def status; end

  # pkg:gem/async-websocket#lib/async/websocket/connect_request.rb:36
  def stream; end

  # pkg:gem/async-websocket#lib/async/websocket/connect_request.rb:36
  def stream=(_arg0); end

  # pkg:gem/async-websocket#lib/async/websocket/connect_request.rb:38
  def stream?; end

  # pkg:gem/async-websocket#lib/async/websocket/connect_request.rb:31
  def unwrap; end
end

# The response from the server back to the client for negotiating HTTP/2 WebSockets.
#
# pkg:gem/async-websocket#lib/async/websocket/connect_response.rb:12
class Async::WebSocket::ConnectResponse < ::Protocol::HTTP::Response
  include ::Protocol::WebSocket::Headers

  # pkg:gem/async-websocket#lib/async/websocket/connect_response.rb:15
  def initialize(request, headers = T.unsafe(nil), protocol: T.unsafe(nil), &block); end
end

# This is a basic synchronous websocket client:
#
# pkg:gem/async-websocket#lib/async/websocket/connection.rb:17
class Async::WebSocket::Connection < ::Protocol::WebSocket::Connection
  include ::Protocol::WebSocket::Headers

  # pkg:gem/async-websocket#lib/async/websocket/connection.rb:34
  def initialize(framer, protocol = T.unsafe(nil), **options); end

  # pkg:gem/async-websocket#lib/async/websocket/connection.rb:46
  def inspect; end

  # pkg:gem/async-websocket#lib/async/websocket/connection.rb:44
  def protocol; end

  # pkg:gem/async-websocket#lib/async/websocket/connection.rb:40
  def reusable?; end

  class << self
    # pkg:gem/async-websocket#lib/async/websocket/connection.rb:20
    def call(framer, protocol = T.unsafe(nil), extensions = T.unsafe(nil), **options); end
  end
end

# pkg:gem/async-websocket#lib/async/websocket/error.rb:19
class Async::WebSocket::ConnectionError < ::Async::WebSocket::Error
  # pkg:gem/async-websocket#lib/async/websocket/error.rb:20
  def initialize(message, response); end

  # The failed HTTP response.
  #
  # pkg:gem/async-websocket#lib/async/websocket/error.rb:27
  def response; end
end

# pkg:gem/async-websocket#lib/async/websocket/error.rb:13
class Async::WebSocket::Error < ::Protocol::WebSocket::Error; end

# pkg:gem/async-websocket#lib/async/websocket/connection.rb:14
Async::WebSocket::Frame = Protocol::WebSocket::Frame

# pkg:gem/async-websocket#lib/async/websocket/error.rb:10
class Async::WebSocket::ProtocolError < ::Protocol::WebSocket::ProtocolError; end

# pkg:gem/async-websocket#lib/async/websocket/request.rb:12
class Async::WebSocket::Request
  include ::Protocol::WebSocket::Headers

  # pkg:gem/async-websocket#lib/async/websocket/request.rb:19
  def initialize(scheme = T.unsafe(nil), authority = T.unsafe(nil), path = T.unsafe(nil), headers = T.unsafe(nil), **options, &block); end

  # pkg:gem/async-websocket#lib/async/websocket/request.rb:35
  def authority; end

  # pkg:gem/async-websocket#lib/async/websocket/request.rb:35
  def authority=(_arg0); end

  # pkg:gem/async-websocket#lib/async/websocket/request.rb:39
  def body; end

  # pkg:gem/async-websocket#lib/async/websocket/request.rb:39
  def body=(_arg0); end

  # Send the request to the given connection.
  #
  # pkg:gem/async-websocket#lib/async/websocket/request.rb:42
  def call(connection); end

  # pkg:gem/async-websocket#lib/async/websocket/request.rb:37
  def headers; end

  # pkg:gem/async-websocket#lib/async/websocket/request.rb:37
  def headers=(_arg0); end

  # pkg:gem/async-websocket#lib/async/websocket/request.rb:52
  def idempotent?; end

  # pkg:gem/async-websocket#lib/async/websocket/request.rb:36
  def path; end

  # pkg:gem/async-websocket#lib/async/websocket/request.rb:36
  def path=(_arg0); end

  # pkg:gem/async-websocket#lib/async/websocket/request.rb:30
  def protocol; end

  # pkg:gem/async-websocket#lib/async/websocket/request.rb:34
  def scheme; end

  # pkg:gem/async-websocket#lib/async/websocket/request.rb:34
  def scheme=(_arg0); end

  # pkg:gem/async-websocket#lib/async/websocket/request.rb:56
  def to_s; end

  class << self
    # pkg:gem/async-websocket#lib/async/websocket/request.rb:15
    def websocket?(request); end
  end
end

# pkg:gem/async-websocket#lib/async/websocket/response.rb:13
module Async::WebSocket::Response
  class << self
    # Send the request to the given connection.
    #
    # pkg:gem/async-websocket#lib/async/websocket/response.rb:15
    def for(request, headers = T.unsafe(nil), **options, &body); end
  end
end

# pkg:gem/async-websocket#lib/async/websocket/server.rb:14
class Async::WebSocket::Server < ::Protocol::HTTP::Middleware
  include ::Protocol::WebSocket::Headers

  # pkg:gem/async-websocket#lib/async/websocket/server.rb:17
  def initialize(delegate, **options, &block); end

  # pkg:gem/async-websocket#lib/async/websocket/server.rb:24
  def call(request); end
end

# pkg:gem/async-websocket#lib/async/websocket/error.rb:16
class Async::WebSocket::UnsupportedVersionError < ::Async::WebSocket::Error; end

# This is required for HTTP/1.x to upgrade the connection to the WebSocket protocol.
# See https://tools.ietf.org/html/rfc6455
#
# pkg:gem/async-websocket#lib/async/websocket/upgrade_request.rb:20
class Async::WebSocket::UpgradeRequest < ::Protocol::HTTP::Request
  include ::Protocol::WebSocket::Headers

  # pkg:gem/async-websocket#lib/async/websocket/upgrade_request.rb:57
  def initialize(request, protocols: T.unsafe(nil), version: T.unsafe(nil), &block); end

  # pkg:gem/async-websocket#lib/async/websocket/upgrade_request.rb:72
  def call(connection); end
end

# pkg:gem/async-websocket#lib/async/websocket/upgrade_request.rb:23
class Async::WebSocket::UpgradeRequest::Wrapper
  # pkg:gem/async-websocket#lib/async/websocket/upgrade_request.rb:24
  def initialize(response, verified:); end

  # pkg:gem/async-websocket#lib/async/websocket/upgrade_request.rb:30
  def close; end

  # pkg:gem/async-websocket#lib/async/websocket/upgrade_request.rb:48
  def headers; end

  # pkg:gem/async-websocket#lib/async/websocket/upgrade_request.rb:38
  def response; end

  # pkg:gem/async-websocket#lib/async/websocket/upgrade_request.rb:38
  def response=(_arg0); end

  # pkg:gem/async-websocket#lib/async/websocket/upgrade_request.rb:44
  def status; end

  # pkg:gem/async-websocket#lib/async/websocket/upgrade_request.rb:52
  def stream; end

  # pkg:gem/async-websocket#lib/async/websocket/upgrade_request.rb:40
  def stream?; end

  # pkg:gem/async-websocket#lib/async/websocket/upgrade_request.rb:34
  def unwrap; end
end

# The response from the server back to the client for negotiating HTTP/1.x WebSockets.
#
# pkg:gem/async-websocket#lib/async/websocket/upgrade_response.rb:14
class Async::WebSocket::UpgradeResponse < ::Protocol::HTTP::Response
  include ::Protocol::WebSocket::Headers

  # pkg:gem/async-websocket#lib/async/websocket/upgrade_response.rb:17
  def initialize(request, headers = T.unsafe(nil), protocol: T.unsafe(nil), &block); end
end

# pkg:gem/async-websocket#lib/async/websocket/version.rb:8
Async::WebSocket::VERSION = T.let(T.unsafe(nil), String)
