# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `async-utilization` gem.
# Please instead update this file by running `bin/tapioca gem async-utilization`.


# @namespace
# Released under the MIT License.
# Copyright, 2026, by Samuel Williams.
#
# pkg:gem/async-utilization#lib/async/utilization/version.rb:7
module Async; end

# Provides high-performance utilization metrics for Async services using shared memory.
#
# This module provides a convenient interface for tracking utilization metrics
# that can be synchronized to shared memory for inter-process communication.
# Registries should be explicitly created and passed to components that need them.
#
# See the {file:guides/getting-started/readme.md Getting Started} guide for usage examples.
# @namespace
#
# pkg:gem/async-utilization#lib/async/utilization/version.rb:9
module Async::Utilization; end

# A cached metric reference that avoids hash lookups on the fast path.
#
# This class caches all the details needed to write directly to shared memory,
# including the buffer, offset, and type. When the observer changes, the cache
# is invalidated and rebuilt on the next access.
#
# pkg:gem/async-utilization#lib/async/utilization/metric.rb:13
class Async::Utilization::Metric
  # Initialize a new metric.
  #
  # @parameter name [Symbol] The field name for this metric.
  #
  # pkg:gem/async-utilization#lib/async/utilization/metric.rb:28
  def initialize(name); end

  # Decrement the metric value.
  #
  # Uses the fast path (direct buffer write) when cache is valid and observer is available.
  #
  # @returns [Integer] The new value of the field.
  #
  # pkg:gem/async-utilization#lib/async/utilization/metric.rb:112
  def decrement; end

  # Increment the metric value.
  #
  # @returns [Integer] The new value of the field.
  #
  # pkg:gem/async-utilization#lib/async/utilization/metric.rb:80
  def increment; end

  # @attribute [Symbol] The field name for this metric.
  #
  # pkg:gem/async-utilization#lib/async/utilization/metric.rb:39
  def name; end

  # Set the observer and rebuild cache.
  #
  # This is called when the registry assigns a new observer (or removes it).
  # The cache is invalidated and then immediately recomputed so that the
  # fast write path doesn't need to re-check the observer on the first write.
  #
  # @parameter observer [Observer | Nil] The new observer (or nil).
  #
  # pkg:gem/async-utilization#lib/async/utilization/metric.rb:57
  def observer=(observer); end

  # Set the metric value.
  #
  # Uses the fast path (direct buffer write) when cache is valid and observer is available.
  #
  # @parameter value [Numeric] The value to set.
  #
  # pkg:gem/async-utilization#lib/async/utilization/metric.rb:126
  def set(value); end

  # Track an operation: increment before the block, decrement after it completes.
  #
  # Returns the block's return value. Use for active/count metrics that should
  # reflect the number of operations currently in progress.
  #
  # @yield The operation to track.
  # @returns [Object] The block's return value.
  #
  # pkg:gem/async-utilization#lib/async/utilization/metric.rb:96
  def track(&block); end

  # Get the current in-memory metric value.
  #
  # @returns [Numeric] The last value written to this metric.
  #
  # pkg:gem/async-utilization#lib/async/utilization/metric.rb:44
  def value; end

  protected

  # Write directly to the cached buffer if available.
  #
  # This is the fast path that avoids hash lookups. Always ensures cache is valid
  # first. If there's no observer or buffer, silently does nothing.
  #
  # @parameter value [Numeric] The value to write.
  # @returns [Boolean] Whether the write succeeded.
  #
  # pkg:gem/async-utilization#lib/async/utilization/metric.rb:142
  def write_direct(value); end

  class << self
    # Create a new metric for the given field and observer.
    #
    # @parameter field [Symbol] The field name for this metric.
    # @parameter observer [Observer | Nil] The observer to associate with this metric.
    # @returns [Metric] A new metric instance.
    #
    # pkg:gem/async-utilization#lib/async/utilization/metric.rb:19
    def for(field, observer); end
  end
end

# A registry-like view that prefixes metric names.
#
# Namespaces let components use generic metric names while applications decide
# how those names are composed in the shared registry.
#
# pkg:gem/async-utilization#lib/async/utilization/namespace.rb:12
class Async::Utilization::Namespace
  # Initialize a new namespace.
  #
  # @parameter registry [Registry] The underlying registry.
  # @parameter name [Symbol] The namespace name.
  #
  # pkg:gem/async-utilization#lib/async/utilization/namespace.rb:17
  def initialize(registry, name); end

  # Get a metric in this namespace.
  #
  # @parameter name [Symbol] The metric name.
  # @returns [Metric] A metric instance for the namespaced field.
  #
  # pkg:gem/async-utilization#lib/async/utilization/namespace.rb:32
  def metric(name); end

  # @attribute [Symbol] The namespace name.
  #
  # pkg:gem/async-utilization#lib/async/utilization/namespace.rb:26
  def name; end

  # Get a nested namespace.
  #
  # @parameter name [Symbol] The nested namespace name.
  # @returns [Namespace] A namespace view with the composed name.
  #
  # pkg:gem/async-utilization#lib/async/utilization/namespace.rb:40
  def namespace(name); end

  # @attribute [Registry] The underlying registry.
  #
  # pkg:gem/async-utilization#lib/async/utilization/namespace.rb:23
  def registry; end

  private

  # pkg:gem/async-utilization#lib/async/utilization/namespace.rb:46
  def metric_name(name); end
end

# Shared memory observer for utilization metrics.
#
# Writes metrics to shared memory using a schema to define the
# serialization layout. The schema is required to know how to
# serialize values efficiently.
#
# pkg:gem/async-utilization#lib/async/utilization/observer.rb:15
class Async::Utilization::Observer
  # Initialize a new shared memory observer.
  #
  # @parameter schema [Schema] The schema defining field types and layout.
  # @parameter buffer [IO::Buffer] The mapped buffer for shared memory.
  #
  # pkg:gem/async-utilization#lib/async/utilization/observer.rb:63
  def initialize(schema, buffer); end

  # @attribute [IO::Buffer] The mapped buffer for shared memory.
  #
  # pkg:gem/async-utilization#lib/async/utilization/observer.rb:72
  def buffer; end

  # @attribute [Schema] The schema used for serialization.
  #
  # pkg:gem/async-utilization#lib/async/utilization/observer.rb:69
  def schema; end

  class << self
    # Open a shared memory observer from a file.
    #
    # Maps the shared memory file and creates an Observer instance.
    # The file descriptor is closed after mapping - the memory mapping
    # persists independently on Unix/Linux systems.
    #
    # Note: mmap requires page-aligned offsets and sizes. This method handles
    # non-page-aligned offsets by mapping from the nearest page boundary
    # and adjusting field offsets accordingly.
    #
    # @parameter schema [Schema] The schema defining field types and layout.
    # @parameter path [String] Path to the shared memory file.
    # @parameter size [Integer] Size of the shared memory region to map.
    # @parameter offset [Integer] Offset into the shared memory buffer.
    # @returns [Observer] A new Observer instance.
    #
    # pkg:gem/async-utilization#lib/async/utilization/observer.rb:31
    def open(schema, path, size, offset); end
  end
end

# Registry for emitting utilization metrics.
#
# The registry tracks values directly and notifies a registered observer
# when values change. The observer (like Observer) can write to its backend.
#
# Registries should be explicitly created and passed to components that need them.
# In service contexts, registries are typically created via the evaluator and
# shared across components within the same service instance.
#
# When an observer is added, it is immediately notified of all current values
# so it can sync its state. When values change, the observer is notified.
#
# @example Create a registry and emit metrics:
# 	registry = Async::Utilization::Registry.new
#
# 	total_requests = registry.metric(:total_requests)
# 	total_requests.increment
#
# 	active_requests = registry.metric(:active_requests)
# 	active_requests.track do
# 		# Handle request - auto-decrements when block completes
# 	end
#
# 	# Add shared memory observer when supervisor connects
# 	# Observer will be notified of all current values automatically
# 	schema = Async::Utilization::Schema.build(
# 		total_requests: :u64,
# 		active_requests: :u32
# 	)
# 	observer = Async::Utilization::Observer.open(schema, "/path/to/shm", 4096, 0)
# 	registry.observer = observer
#
# pkg:gem/async-utilization#lib/async/utilization/registry.rb:42
class Async::Utilization::Registry
  # Initialize a new registry.
  #
  # pkg:gem/async-utilization#lib/async/utilization/registry.rb:44
  def initialize; end

  # Get a cached metric reference for a field.
  #
  # Returns a {Metric} instance that caches all details needed for fast writes.
  # Metrics are cached per field and invalidated when the observer changes.
  #
  # @parameter field [Symbol] The field name to get a metric for.
  # @returns [Metric] A metric instance for the given field.
  #
  # pkg:gem/async-utilization#lib/async/utilization/registry.rb:90
  def metric(field); end

  # Get a namespace view of this registry.
  #
  # @parameter name [Symbol] The namespace name.
  # @returns [Namespace] A registry-like namespace view.
  #
  # pkg:gem/async-utilization#lib/async/utilization/registry.rb:102
  def namespace(name); end

  # @attribute [Object | Nil] The registered observer.
  #
  # pkg:gem/async-utilization#lib/async/utilization/registry.rb:52
  def observer; end

  # Set the observer for the registry.
  #
  # When an observer is set, all cached metrics are updated so they write
  # directly to the observer's buffer. The observer must expose `schema`
  # and `buffer` attributes.
  #
  # @parameter observer [Observer | Nil] The observer to set.
  #
  # pkg:gem/async-utilization#lib/async/utilization/registry.rb:70
  def observer=(observer); end

  # Get the current values for all metrics.
  #
  # @returns [Hash] Hash mapping field names to their current values.
  #
  # pkg:gem/async-utilization#lib/async/utilization/registry.rb:57
  def values; end
end

# Defines a schema for shared memory serialization.
#
# The schema defines the layout and types for serializing utilization
# metrics to shared memory. It's only needed when using Observer for
# shared memory storage - the Registry itself doesn't require a schema.
#
# @example Assign a schema to an observer:
# 	schema = Async::Utilization::Schema.build(
# 		total_requests: :u64,
# 		active_requests: :u32,
# 	)
#
# 	registry = Async::Utilization::Registry.new
# 	observer = Async::Utilization::Observer.open(schema, "/path/to/shm", 4096, 0)
# 	registry.observer = observer
#
# pkg:gem/async-utilization#lib/async/utilization/schema.rb:23
class Async::Utilization::Schema
  # Initialize a new schema.
  #
  # @parameter fields [Array<Field>] Array of Field instances.
  #
  # pkg:gem/async-utilization#lib/async/utilization/schema.rb:49
  def initialize(fields); end

  # Get field information for a given field.
  #
  # @parameter field [Symbol] The field name to look up.
  # @returns [Field] Field object containing name, type and offset, or nil if field not found.
  #
  # pkg:gem/async-utilization#lib/async/utilization/schema.rb:67
  def [](field); end

  # @attribute [Array<Field>] The fields in this schema.
  #
  # pkg:gem/async-utilization#lib/async/utilization/schema.rb:61
  def fields; end

  # Convert schema to array format for shared memory.
  #
  # @returns [Array] Array of [key, type, offset] tuples.
  #
  # pkg:gem/async-utilization#lib/async/utilization/schema.rb:74
  def to_a; end

  class << self
    # Build a schema from raw fields.
    #
    # Factory method that takes a hash of field names to types and creates
    # Field instances with calculated offsets.
    #
    # @parameter fields [Hash] Hash mapping field names to IO::Buffer type symbols (:u32, :u64, :i32, :i64, :f32, :f64).
    # @returns [Schema] A new schema instance.
    #
    # pkg:gem/async-utilization#lib/async/utilization/schema.rb:34
    def build(fields); end
  end
end

# Represents a field in the schema with its name, type, and offset.
#
# pkg:gem/async-utilization#lib/async/utilization/schema.rb:25
class Async::Utilization::Schema::Field < ::Data
  # pkg:gem/async-utilization#lib/async/utilization/schema.rb:25
  def name; end

  # pkg:gem/async-utilization#lib/async/utilization/schema.rb:25
  def offset; end

  # pkg:gem/async-utilization#lib/async/utilization/schema.rb:25
  def type; end

  class << self
    # pkg:gem/async-utilization#lib/async/utilization/schema.rb:25
    def [](*_arg0); end

    # pkg:gem/async-utilization#lib/async/utilization/schema.rb:25
    def inspect; end

    # pkg:gem/async-utilization#lib/async/utilization/schema.rb:25
    def members; end

    # pkg:gem/async-utilization#lib/async/utilization/schema.rb:25
    def new(*_arg0); end
  end
end

# Represents a shared memory segment store for utilization data.
#
# Stores fixed-size segments in a shared memory file, associates each
# segment with a utilization schema, and reads the resulting values.
#
# pkg:gem/async-utilization#lib/async/utilization/segment_store.rb:14
class Async::Utilization::SegmentStore
  # Initialize the shared memory segment store.
  #
  # @parameter file [File] The open shared memory file.
  # @parameter buffer [IO::Buffer] The mapped shared memory buffer.
  # @parameter size [Integer] The initial size of the shared memory file.
  # @parameter segment_size [Integer] The size of each allocation segment.
  # @parameter growth_factor [Integer | Float] The factor used to grow the file when all segments are allocated.
  #
  # pkg:gem/async-utilization#lib/async/utilization/segment_store.rb:70
  def initialize(file, buffer, size:, segment_size:, growth_factor:); end

  # Allocate a segment for the given key.
  #
  # The shared memory file is automatically resized if no segments are available.
  #
  # @parameter key [Object] The key used to identify the allocation.
  # @parameter schema [Array] The `[key, type, offset]` tuples describing the data layout.
  # @returns [Integer | Nil] The offset into the shared memory file, or `nil` if allocation fails.
  #
  # pkg:gem/async-utilization#lib/async/utilization/segment_store.rb:92
  def allocate(key, schema); end

  # Get the allocation information for the given key.
  #
  # @parameter key [Object] The key used to identify the allocation.
  # @returns [Hash | Nil] The allocation offset and schema, or `nil` if the key is not allocated.
  #
  # pkg:gem/async-utilization#lib/async/utilization/segment_store.rb:118
  def allocation(key); end

  # Close the shared memory file.
  #
  # pkg:gem/async-utilization#lib/async/utilization/segment_store.rb:199
  def close; end

  # Free the segment allocated to the given key.
  #
  # @parameter key [Object] The key used to identify the allocation.
  #
  # pkg:gem/async-utilization#lib/async/utilization/segment_store.rb:108
  def free(key); end

  # Read utilization data from an allocated segment.
  #
  # @parameter key [Object] The key used to identify the allocation.
  # @returns [Hash | Nil] The utilization values, or `nil` if the key is not allocated.
  #
  # pkg:gem/async-utilization#lib/async/utilization/segment_store.rb:139
  def read(key); end

  # Resize the shared memory file.
  #
  # The new size is rounded up to the nearest page boundary.
  #
  # @parameter new_size [Integer] The requested new size of the shared memory file.
  # @returns [Boolean] Whether the file was resized successfully.
  #
  # pkg:gem/async-utilization#lib/async/utilization/segment_store.rb:166
  def resize(new_size); end

  # @attribute [Integer] The current size of the shared memory file.
  #
  # pkg:gem/async-utilization#lib/async/utilization/segment_store.rb:123
  def size; end

  # Update the schema for an existing allocation.
  #
  # @parameter key [Object] The key used to identify the allocation.
  # @parameter schema [Array] The `[key, type, offset]` tuples describing the data layout.
  #
  # pkg:gem/async-utilization#lib/async/utilization/segment_store.rb:129
  def update_schema(key, schema); end

  class << self
    # Open a shared memory segment store.
    #
    # @parameter path [String] The path to the shared memory file.
    # @parameter size [Integer] The initial size of the shared memory file.
    # @parameter segment_size [Integer] The size of each allocation segment.
    # @parameter growth_factor [Integer | Float] The factor used to grow the file when all segments are allocated.
    # @parameter replace [Boolean] Whether to replace an existing file at the given path.
    # @yields {|store| ...} The store, which is closed after the block completes.
    # 	@parameter store [SegmentStore] The opened store.
    # @returns [SegmentStore | Object] The store, or the value returned by the block.
    # @raises [ArgumentError] If the store configuration is invalid.
    # @raises [Errno::EEXIST] If the path already exists and `replace` is `false`.
    #
    # pkg:gem/async-utilization#lib/async/utilization/segment_store.rb:27
    def open(path, size: T.unsafe(nil), segment_size: T.unsafe(nil), growth_factor: T.unsafe(nil), replace: T.unsafe(nil)); end
  end
end

# pkg:gem/async-utilization#lib/async/utilization/version.rb:10
Async::Utilization::VERSION = T.let(T.unsafe(nil), String)
