# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `falcon` gem.
# Please instead update this file by running `bin/tapioca gem falcon`.


# Released under the MIT License.
# Copyright, 2019-2026, by Samuel Williams.
# Released under the MIT License.
# Copyright, 2024-2026, by Samuel Williams.
# Released under the MIT License.
# Copyright, 2026, by Samuel Williams.
# Released under the MIT License.
# Copyright, 2020-2026, by Samuel Williams.
# @namespace
#
# pkg:gem/falcon#lib/falcon/version.rb:7
module Falcon; end

# @namespace
#
# pkg:gem/falcon#lib/falcon/body/request_finished.rb:10
module Falcon::Body; end

# Wraps a response body and decrements a metric after the body is closed.
#
# Runs close on the underlying body first (which invokes rack.response_finished),
# then decrements the metric, even if closing raises. Use this so requests_active
# stays elevated until the request is fully finished (including response_finished
# callbacks), without leaking if close reports an error.
#
# pkg:gem/falcon#lib/falcon/body/request_finished.rb:17
class Falcon::Body::RequestFinished < ::Protocol::HTTP::Body::Wrapper
  # Initialize the wrapper.
  #
  # @parameter body [Protocol::HTTP::Body::Readable] The body to wrap.
  # @parameter metric [Async::Utilization::Metric] The metric to decrement on close.
  #
  # pkg:gem/falcon#lib/falcon/body/request_finished.rb:39
  def initialize(body, metric); end

  # Closes the underlying body (invoking rack.response_finished), then decrements the metric.
  #
  # @parameter error [Exception, nil] Optional error that caused the close.
  #
  # pkg:gem/falcon#lib/falcon/body/request_finished.rb:58
  def close(error = T.unsafe(nil)); end

  # @returns [Boolean] False, rewinding is not supported.
  #
  # pkg:gem/falcon#lib/falcon/body/request_finished.rb:51
  def rewind; end

  # @returns [Boolean] False, the wrapper does not support rewinding.
  #
  # pkg:gem/falcon#lib/falcon/body/request_finished.rb:46
  def rewindable?; end

  class << self
    # Wrap a response body with a metric.
    #
    # Expects the caller to have incremented `requests_active` beforehand. If the body is not wrapped (nil or empty message/body, or an error while assigning the wrapper), the `ensure` block decrements once. When wrapped, the metric is decremented in {#close}.
    #
    # @parameter message [Protocol::HTTP::Response] The response whose body to wrap.
    # @parameter metric [Async::Utilization::Metric] The metric to decrement when the body is closed.
    # @returns [Protocol::HTTP::Response] The message (modified in place).
    #
    # pkg:gem/falcon#lib/falcon/body/request_finished.rb:25
    def wrap(message, metric); end
  end
end

# A composite server that manages multiple {Server} instances.
#
# This class coordinates running multiple server instances concurrently, allowing you to:
# - Serve different applications on different endpoints.
# - Use different configurations per server.
# - Access statistics for each named server.
# - Control all servers as a single unit.
#
# @example Create and run several applications.
# 	require 'falcon/composite_server'
# 	require 'falcon/server'
#
# 	# Create individual servers
# 	servers = {
# 	  "http" => Falcon::Server.new(app1, endpoint1),
# 	  "https" => Falcon::Server.new(app2, endpoint2)
# 	}
#
# 	# Create the composite server
# 	composite = Falcon::CompositeServer.new(servers)
#
# 	# Run all servers
# 	composite.run
#
# pkg:gem/falcon#lib/falcon/composite_server.rb:32
class Falcon::CompositeServer
  # Initialize a composite server with the given server instances.
  #
  # @parameter servers [Hash(String, Falcon::Server)] A hash mapping server names to server instances.
  #
  # pkg:gem/falcon#lib/falcon/composite_server.rb:36
  def initialize(servers); end

  # Get detailed statistics for each server.
  #
  # @returns [Hash(String, String)] A hash mapping server names to their statistics strings.
  #
  # pkg:gem/falcon#lib/falcon/composite_server.rb:73
  def detailed_statistics; end

  # Run the composite server, starting all individual servers.
  #
  # This method should be called within an Async context. It will run all server instances concurrently.
  #
  # @returns [Async::Task] The task running the servers. Call `stop` on the returned task to stop all servers.
  #
  # pkg:gem/falcon#lib/falcon/composite_server.rb:49
  def run; end

  # The individual server instances mapped by name.
  # @attribute [Hash(String, Falcon::Server)]
  #
  # pkg:gem/falcon#lib/falcon/composite_server.rb:42
  def servers; end

  # Generates a human-readable string representing statistics for all servers.
  #
  # @returns [String] A string representing the current statistics for each server.
  #
  # pkg:gem/falcon#lib/falcon/composite_server.rb:64
  def statistics_string; end
end

# Describes a bound listener for a Falcon server.
#
# pkg:gem/falcon#lib/falcon/listener.rb:8
class Falcon::Listener
  # Initialize a bound listener.
  # @parameter name [String] The logical listener name.
  # @parameter scheme [String] The application protocol scheme.
  # @parameter protocols [Array(String)] The supported application protocol names.
  # @parameter endpoint [IO::Endpoint::BoundEndpoint] The bound endpoint.
  #
  # pkg:gem/falcon#lib/falcon/listener.rb:14
  def initialize(name:, scheme:, protocols:, endpoint:); end

  # @attribute [Array(Addrinfo)] The bound addresses.
  #
  # pkg:gem/falcon#lib/falcon/listener.rb:36
  def addresses; end

  # Close the bound endpoint.
  #
  # pkg:gem/falcon#lib/falcon/listener.rb:39
  def close; end

  # @attribute [IO::Endpoint::BoundEndpoint] The bound endpoint.
  #
  # pkg:gem/falcon#lib/falcon/listener.rb:33
  def endpoint; end

  # @attribute [String] The logical listener name.
  #
  # pkg:gem/falcon#lib/falcon/listener.rb:24
  def name; end

  # @attribute [Array(String)] The supported application protocol names.
  #
  # pkg:gem/falcon#lib/falcon/listener.rb:30
  def protocols; end

  # @attribute [String] The application protocol scheme.
  #
  # pkg:gem/falcon#lib/falcon/listener.rb:27
  def scheme; end
end

# @namespace
#
# pkg:gem/falcon#lib/falcon/middleware/verbose.rb:10
module Falcon::Middleware; end

# A HTTP middleware for logging requests and responses.
#
# pkg:gem/falcon#lib/falcon/middleware/verbose.rb:12
class Falcon::Middleware::Verbose < ::Protocol::HTTP::Middleware
  # Initialize the verbose middleware.
  # @parameter app [Protocol::HTTP::Middleware] The middleware to wrap.
  # @parameter logger [Console::Logger] The logger to use.
  #
  # pkg:gem/falcon#lib/falcon/middleware/verbose.rb:16
  def initialize(app, logger = T.unsafe(nil)); end

  # Log details of the incoming request.
  #
  # pkg:gem/falcon#lib/falcon/middleware/verbose.rb:23
  def annotate(request); end

  # Log details of the incoming request using {annotate} and wrap the response to log response details too.
  #
  # pkg:gem/falcon#lib/falcon/middleware/verbose.rb:33
  def call(request); end
end

# A server listening on a specific endpoint, hosting a specific middleware.
#
# pkg:gem/falcon#lib/falcon/server.rb:19
class Falcon::Server < ::Async::HTTP::Server
  # Initialize the server and set up statistics tracking.
  #
  # @parameter utilization_registry [Registry, nil] The utilization registry to use for metrics tracking.
  #   If nil, a new registry instance is created.
  #
  # pkg:gem/falcon#lib/falcon/server.rb:58
  def initialize(*arguments, utilization_registry: T.unsafe(nil), **options); end

  # Accept a new connection and track connection statistics.
  #
  # pkg:gem/falcon#lib/falcon/server.rb:71
  def accept(*, **, &); end

  # Handle a request and track request statistics.
  #
  # Uses manual increment/decrement so requests_active stays elevated until the
  # response body is closed (including rack.response_finished). The
  # Body::RequestFinished wrapper runs the decrement after the body closes,
  # so response_finished callbacks are counted as active.
  #
  # pkg:gem/falcon#lib/falcon/server.rb:84
  def call(*, **, &); end

  # Generates a human-readable string representing the current statistics.
  #
  # e.g. `C=23/3.42K R=2/3.42K L=0.273`
  #
  # This can be interpreted as:
  #
  # - `C=23/3.42K` - The number of connections currently open and the total number of connections accepted.
  # - `R=2/3.42K` - The number of requests currently being processed and the total number of requests received.
  # - `L=0.273` - The average scheduler load of the server, where 0.0 is idle and 1.0 is fully loaded.
  #
  # @returns [String] A string representing the current statistics.
  #
  # pkg:gem/falcon#lib/falcon/server.rb:114
  def statistics_string; end

  private

  # pkg:gem/falcon#lib/falcon/server.rb:120
  def format_count(value); end

  class << self
    # @deprecated Use {rack_middleware} instead.
    #
    # pkg:gem/falcon#lib/falcon/server.rb:21
    def middleware(*, **, &); end

    # Wrap a protocol application with the standard server middleware.
    # @parameter application [Protocol::HTTP::Middleware] The protocol application/middleware.
    # @parameter verbose [Boolean] Whether to add the {Middleware::Verbose} middleware.
    # @parameter cache [Boolean] Whether to add the {Async::HTTP::Cache} middleware.
    #
    # pkg:gem/falcon#lib/falcon/server.rb:39
    def protocol_middleware(application, verbose: T.unsafe(nil), cache: T.unsafe(nil)); end

    # Wrap a Rack application with the standard server middleware.
    # @parameter rack_app [Proc | Object] A rack application/middleware.
    # @parameter verbose [Boolean] Whether to add the {Middleware::Verbose} middleware.
    # @parameter cache [Boolean] Whether to add the {Async::HTTP::Cache} middleware.
    #
    # pkg:gem/falcon#lib/falcon/server.rb:31
    def rack_middleware(rack_app, verbose: T.unsafe(nil), cache: T.unsafe(nil)); end
  end
end

# pkg:gem/falcon#lib/falcon/version.rb:8
Falcon::VERSION = T.let(T.unsafe(nil), String)
