# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `protocol-websocket` gem.
# Please instead update this file by running `bin/tapioca gem protocol-websocket`.


# @namespace
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/error.rb:8
module Protocol; end

# @namespace
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/error.rb:9
module Protocol::WebSocket; end

# Represents a binary frame that is sent or received by a WebSocket connection.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/binary_frame.rb:13
class Protocol::WebSocket::BinaryFrame < ::Protocol::WebSocket::Frame
  # Apply this frame to the specified connection.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/binary_frame.rb:28
  def apply(connection); end

  # @returns [Boolean] if the frame contains data.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/binary_frame.rb:17
  def data?; end

  # Decode the binary buffer into a suitable binary message.
  # @parameter buffer [String] The binary data to unpack.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/binary_frame.rb:23
  def read_message(buffer); end
end

# pkg:gem/protocol-websocket#lib/protocol/websocket/binary_frame.rb:14
Protocol::WebSocket::BinaryFrame::OPCODE = T.let(T.unsafe(nil), Integer)

# Represents a binary message that can be sent or received over a WebSocket connection.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/message.rb:72
class Protocol::WebSocket::BinaryMessage < ::Protocol::WebSocket::Message
  # Send this message as a binary frame over the given connection.
  # @parameter connection [Connection] The WebSocket connection to send through.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/message.rb:75
  def send(connection, **options); end
end

# Represents a close frame that is sent or received by a WebSocket connection.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/close_frame.rb:12
class Protocol::WebSocket::CloseFrame < ::Protocol::WebSocket::Frame
  # Apply this frame to the specified connection.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/close_frame.rb:71
  def apply(connection); end

  # Pack a close code and reason into the frame data.
  # If code is missing, reason is ignored.
  # @parameter code [Integer | Nil] The close code.
  # @parameter reason [String | Nil] The close reason.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/close_frame.rb:50
  def pack(code = T.unsafe(nil), reason = T.unsafe(nil)); end

  # Generate a suitable reply.
  # @returns [CloseFrame]
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/close_frame.rb:64
  def reply(code = T.unsafe(nil), reason = T.unsafe(nil)); end

  # Unpack the frame data into a close code and reason.
  # @returns [Tuple(Integer, String)] The close code and reason.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/close_frame.rb:18
  def unpack; end
end

# pkg:gem/protocol-websocket#lib/protocol/websocket/close_frame.rb:14
Protocol::WebSocket::CloseFrame::FORMAT = T.let(T.unsafe(nil), String)

# pkg:gem/protocol-websocket#lib/protocol/websocket/close_frame.rb:13
Protocol::WebSocket::CloseFrame::OPCODE = T.let(T.unsafe(nil), Integer)

# The connection was closed, maybe unexpectedly.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/error.rb:58
class Protocol::WebSocket::ClosedError < ::Protocol::WebSocket::ProtocolError; end

# @namespace
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/coder/json.rb:10
module Protocol::WebSocket::Coder; end

# The default coder for WebSocket messages.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/coder.rb:13
Protocol::WebSocket::Coder::DEFAULT = Protocol::WebSocket::Coder::JSON

# A JSON coder that uses the standard JSON library.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/coder/json.rb:12
module Protocol::WebSocket::Coder::JSON
  class << self
    # Generate a JSON buffer from an object.
    #
    # pkg:gem/protocol-websocket#lib/protocol/websocket/coder/json.rb:19
    def generate(object); end

    # Parse a JSON buffer into an object.
    #
    # pkg:gem/protocol-websocket#lib/protocol/websocket/coder/json.rb:14
    def parse(buffer); end
  end
end

# Wraps a framer and implements for implementing connection specific interactions like reading and writing text.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:13
class Protocol::WebSocket::Connection
  # @parameter mask [String] 4-byte mask to be used for frames generated by this connection.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:15
  def initialize(framer, mask: T.unsafe(nil), **options); end

  # Immediately transition the connection to the closed state *and* close the underlying connection. Any data not yet read will be lost.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:92
  def close(*, **, &); end

  # If not already closed, transition the connection to the closed state and send a close frame.
  # Will try to send a close frame with the specified code and reason, but will ignore any errors that occur while sending.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:72
  def close!(*, **, &); end

  # Close the connection gracefully, sending a close frame with the specified error code and reason. If an error occurs while sending the close frame, the connection will be closed immediately. You may continue to read data from the connection after calling this method, but you should not write any more data.
  #
  # @parameter error [Error | Nil] The error that occurred, if any.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:101
  def close_write(error = T.unsafe(nil)); end

  # @returns [Boolean] if the connection is in the closed state.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:87
  def closed?; end

  # Flush the underlying framer to ensure all buffered data is written to the connection.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:59
  def flush; end

  # @attribute [Framer] The framer which is used for reading and writing frames.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:29
  def framer; end

  # @attribute [Array(Frame)] Buffered frames which form part of a complete message.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:38
  def frames; end

  # @attribute [Array(Frame)] Buffered frames which form part of a complete message.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:38
  def frames=(_arg0); end

  # @attribute [String | Boolean | Nil] The optional mask which is used when generating frames.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:32
  def mask; end

  # Transition the connection to the open state (the default for new connections).
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:64
  def open!; end

  # Pack a binary frame with the specified buffer. This is used by the {#writer} interface.
  # @parameter buffer [String] The binary data to pack into the frame.
  # @returns [BinaryFrame] The packed frame.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:242
  def pack_binary_frame(buffer, **options); end

  # Pack a text frame with the specified buffer. This is used by the {#writer} interface.
  # @parameter buffer [String] The text to pack into the frame.
  # @returns [TextFrame] The packed frame.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:226
  def pack_text_frame(buffer, **options); end

  # Read a message from the connection. If an error occurs while reading the message, the connection will be closed.
  #
  # If the message is fragmented, this method will buffer the frames until a complete message is received.
  #
  # @returns message [Message] The received message.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:298
  def read(**options); end

  # Read a frame from the framer, and apply it to the connection.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:122
  def read_frame; end

  # @attribute [Object] The reader which is used to unpack frames into messages.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:41
  def reader; end

  # @attribute [Object] The reader which is used to unpack frames into messages.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:41
  def reader=(_arg0); end

  # Receive a binary frame for the connection.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:162
  def receive_binary(frame); end

  # Receive a close frame from the connection.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:180
  def receive_close(frame); end

  # Receive a continuation frame for the connection.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:171
  def receive_continuation(frame); end

  # Receive a frame that is not a control frame. By default, this method raises a {ProtocolError}.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:219
  def receive_frame(frame); end

  # Receive a ping frame from the connection.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:205
  def receive_ping(frame); end

  # Receive a pong frame from the connection. By default, this method does nothing.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:214
  def receive_pong(frame); end

  # Receive a text frame from the connection.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:153
  def receive_text(frame); end

  # Reserve a bit in the reserved flags for an extension.
  # @parameter bit [Integer] The bit to reserve, see {Frame::RESERVED} for more details.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:48
  def reserve!(bit); end

  # @attribute [Integer] The allowed reserved bits.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:35
  def reserved; end

  # Send a binary frame with the specified buffer.
  # @parameter buffer [String] The binary data to send.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:251
  def send_binary(buffer, **options); end

  # Send a control frame with data containing a specified control sequence to begin the closing handshake. Does not close the connection, until the remote end responds with a close frame.
  # @parameter code [Integer] The close code to send.
  # @parameter reason [String] The reason for closing the connection.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:258
  def send_close(code = T.unsafe(nil), reason = T.unsafe(nil)); end

  # Send a ping frame with the specified data.
  # @parameter data [String] The data to send in the ping frame.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:193
  def send_ping(data = T.unsafe(nil)); end

  # Send a text frame with the specified buffer.
  # @parameter buffer [String] The text to send.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:235
  def send_text(buffer, **options); end

  # Close the connection gracefully. This will send a close frame and wait for the remote end to respond with a close frame. Any data received after the close frame is sent will be ignored. If you want to process this data, use {#close_write} instead, and read the data before calling {#close}.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:112
  def shutdown; end

  # The default implementation for reading a message buffer. This is used by the {#reader} interface.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:285
  def unpack_frames(frames); end

  # Write a message to the connection.
  # @parameter message [Message] The message to send.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:268
  def write(message, **options); end

  # Write a frame to the framer.
  # Note: This does not immediately write the frame to the connection, you must call {#flush} to ensure the frame is written.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:146
  def write_frame(frame); end

  # @attribute [Object] The writer which is used to pack messages into frames.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:44
  def writer; end

  # @attribute [Object] The writer which is used to pack messages into frames.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/connection.rb:44
  def writer=(_arg0); end
end

# Represents a continuation frame that is sent or received by a WebSocket connection when a message is split into multiple frames.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/continuation_frame.rb:11
class Protocol::WebSocket::ContinuationFrame < ::Protocol::WebSocket::Frame
  # Apply this frame to the specified connection.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/continuation_frame.rb:15
  def apply(connection); end
end

# pkg:gem/protocol-websocket#lib/protocol/websocket/continuation_frame.rb:12
Protocol::WebSocket::ContinuationFrame::OPCODE = T.let(T.unsafe(nil), Integer)

# Represents an error that occurred during the WebSocket protocol negotiation or communication.
# Status codes as defined by <https://tools.ietf.org/html/rfc6455#section-7.4.1>.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/error.rb:12
class Protocol::WebSocket::Error < ::Protocol::HTTP::Error; end

# Indicates that an endpoint is "going away", such as a server going down or a browser having navigated away from a page.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/error.rb:17
Protocol::WebSocket::Error::GOING_AWAY = T.let(T.unsafe(nil), Integer)

# Indicates that a server is terminating the connection because it encountered an unexpected condition that prevented it from fulfilling the request.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/error.rb:39
Protocol::WebSocket::Error::INTERNAL_ERROR = T.let(T.unsafe(nil), Integer)

# Indicates that an endpoint is terminating the connection because it has received a type of data it cannot accept. (e.g., an endpoint that understands only text data MAY send this if it receives a binary message).
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/error.rb:23
Protocol::WebSocket::Error::INVALID_DATA = T.let(T.unsafe(nil), Integer)

# Indicates that an endpoint is terminating the connection because it has received data within a message that was not consistent with the type of the message (e.g., non-UTF-8 data within a text message).
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/error.rb:27
Protocol::WebSocket::Error::INVALID_PAYLOAD = T.let(T.unsafe(nil), Integer)

# Indicates that an endpoint is terminating the connection because it has received a message that is too big for it to process.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/error.rb:33
Protocol::WebSocket::Error::MESSAGE_TOO_LARGE = T.let(T.unsafe(nil), Integer)

# Indicates that an endpoint (client) is terminating the connection because it has expected the server to negotiate one or more extension, but the server didn't return them in the response message of the WebSocket handshake. The list of extensions that are needed should appear in the /reason/ part of the Close frame. Note that this status code is not used by the server, because it can fail the WebSocket handshake instead.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/error.rb:36
Protocol::WebSocket::Error::MISSING_EXTENSION = T.let(T.unsafe(nil), Integer)

# Indicates a normal closure, meaning that the purpose for which the connection was established has been fulfilled.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/error.rb:14
Protocol::WebSocket::Error::NO_ERROR = T.let(T.unsafe(nil), Integer)

# Indicates that an endpoint is terminating the connection because it has received a message that violates its policy. This is a generic status code that can be returned when there is no other more suitable status code (e.g., 1003 or 1009) or if there is a need to hide specific details about the policy.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/error.rb:30
Protocol::WebSocket::Error::POLICY_VIOLATION = T.let(T.unsafe(nil), Integer)

# Indicates that an endpoint is terminating the connection due to a protocol error.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/error.rb:20
Protocol::WebSocket::Error::PROTOCOL_ERROR = T.let(T.unsafe(nil), Integer)

# @namespace
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/extension/compression/constants.rb:10
module Protocol::WebSocket::Extension; end

# Provides support for the permessage-deflate extension.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/extension/compression/constants.rb:11
module Protocol::WebSocket::Extension::Compression
  class << self
    # Accept on the client, the negotiated server response.
    # @parameter options [Hash] a hash of options which are accepted by the client.
    # @parameter arguments [Array(String)] a list of compression parameters as accepted/negotiated by the server.
    #
    # pkg:gem/protocol-websocket#lib/protocol/websocket/extension/compression.rb:95
    def accept(arguments, **options); end

    # @parameter options [Hash] a hash of options which are accepted by the client.
    #
    # pkg:gem/protocol-websocket#lib/protocol/websocket/extension/compression.rb:115
    def client(connection, **options); end

    # Negotiate on the server a response to client based on the incoming client offer.
    # @parameter options [Hash] a hash of options which are accepted by the server.
    # @returns [Array(String)] a list of compression parameters suitable to send back to the client.
    #
    # pkg:gem/protocol-websocket#lib/protocol/websocket/extension/compression.rb:54
    def negotiate(arguments, **options); end

    # Client offer to server, construct a list of requested compression parameters suitable for the `Sec-WebSocket-Extensions` header.
    # @returns [Array(String)] a list of compression parameters suitable to send to the server.
    #
    # pkg:gem/protocol-websocket#lib/protocol/websocket/extension/compression.rb:18
    def offer(client_max_window_bits: T.unsafe(nil), server_max_window_bits: T.unsafe(nil), client_no_context_takeover: T.unsafe(nil), server_no_context_takeover: T.unsafe(nil)); end

    # @parameter options [Hash] a hash of options which are accepted by the server.
    #
    # pkg:gem/protocol-websocket#lib/protocol/websocket/extension/compression.rb:85
    def server(connection, **options); end
  end
end

# Compresses outgoing WebSocket frames using the DEFLATE algorithm.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/extension/compression/deflate.rb:13
class Protocol::WebSocket::Extension::Compression::Deflate
  # Initialize a new deflate compressor.
  # @parameter parent [Object] The parent framer to wrap.
  # @parameter level [Integer] The compression level. Defaults to `Zlib::DEFAULT_COMPRESSION`.
  # @parameter memory_level [Integer] The memory level for compression. Defaults to `Zlib::DEF_MEM_LEVEL`.
  # @parameter strategy [Integer] The compression strategy. Defaults to `Zlib::DEFAULT_STRATEGY`.
  # @parameter window_bits [Integer] The window size in bits for the DEFLATE algorithm.
  # @parameter context_takeover [Boolean] Whether to reuse the compression context across messages.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/extension/compression/deflate.rb:39
  def initialize(parent, level: T.unsafe(nil), memory_level: T.unsafe(nil), strategy: T.unsafe(nil), window_bits: T.unsafe(nil), context_takeover: T.unsafe(nil), **options); end

  # @attribute [Boolean] Whether the compression context is reused across messages.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/extension/compression/deflate.rb:65
  def context_takeover; end

  # Pack a binary frame, optionally compressing the buffer.
  # @parameter buffer [String] The binary payload to pack.
  # @parameter compress [Boolean] Whether to compress the buffer. Defaults to `false`.
  # @returns [Frame] The packed (and optionally compressed) binary frame.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/extension/compression/deflate.rb:89
  def pack_binary_frame(buffer, compress: T.unsafe(nil), **options); end

  # Pack a text frame, optionally compressing the buffer.
  # @parameter buffer [String] The text payload to pack.
  # @parameter compress [Boolean] Whether to compress the buffer. Defaults to `true`.
  # @returns [Frame] The packed (and optionally compressed) text frame.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/extension/compression/deflate.rb:71
  def pack_text_frame(buffer, compress: T.unsafe(nil), **options); end

  # @returns [String] A string representation including window bits and context takeover settings.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/extension/compression/deflate.rb:58
  def to_s; end

  # @attribute [Integer] The window size in bits used for compression.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/extension/compression/deflate.rb:63
  def window_bits; end

  private

  # pkg:gem/protocol-websocket#lib/protocol/websocket/extension/compression/deflate.rb:105
  def deflate(buffer); end

  class << self
    # Client writing to server.
    #
    # pkg:gem/protocol-websocket#lib/protocol/websocket/extension/compression/deflate.rb:15
    def client(parent, client_max_window_bits: T.unsafe(nil), client_no_context_takeover: T.unsafe(nil), **options); end

    # Server writing to client.
    #
    # pkg:gem/protocol-websocket#lib/protocol/websocket/extension/compression/deflate.rb:24
    def server(parent, server_max_window_bits: T.unsafe(nil), server_no_context_takeover: T.unsafe(nil), **options); end
  end
end

# Decompresses incoming WebSocket frames using the DEFLATE algorithm.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/extension/compression/inflate.rb:13
class Protocol::WebSocket::Extension::Compression::Inflate
  # Initialize a new inflate decompressor.
  # @parameter parent [Object] The parent framer to wrap.
  # @parameter context_takeover [Boolean] Whether to reuse the decompression context across messages.
  # @parameter window_bits [Integer] The window size in bits for the DEFLATE algorithm.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/extension/compression/inflate.rb:36
  def initialize(parent, context_takeover: T.unsafe(nil), window_bits: T.unsafe(nil)); end

  # @attribute [Boolean] Whether the decompression context is reused across messages.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/extension/compression/inflate.rb:58
  def context_takeover; end

  # @returns [String] A string representation including window bits and context takeover settings.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/extension/compression/inflate.rb:51
  def to_s; end

  # Unpack and decompress frames into a buffer.
  # @parameter frames [Array(Frame)] The frames to unpack.
  # @returns [String] The decompressed payload buffer.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/extension/compression/inflate.rb:63
  def unpack_frames(frames, **options); end

  # @attribute [Integer] The window size in bits used for decompression.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/extension/compression/inflate.rb:56
  def window_bits; end

  private

  # pkg:gem/protocol-websocket#lib/protocol/websocket/extension/compression/inflate.rb:78
  def inflate(buffer); end

  class << self
    # Client reading from server.
    #
    # pkg:gem/protocol-websocket#lib/protocol/websocket/extension/compression/inflate.rb:15
    def client(parent, server_max_window_bits: T.unsafe(nil), server_no_context_takeover: T.unsafe(nil), **options); end

    # Server reading from client.
    #
    # pkg:gem/protocol-websocket#lib/protocol/websocket/extension/compression/inflate.rb:23
    def server(parent, client_max_window_bits: T.unsafe(nil), client_no_context_takeover: T.unsafe(nil), **options); end
  end
end

# pkg:gem/protocol-websocket#lib/protocol/websocket/extension/compression/inflate.rb:30
Protocol::WebSocket::Extension::Compression::Inflate::TRAILER = T.let(T.unsafe(nil), String)

# Zlib is not capable of handling < 9 window bits.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/extension/compression/constants.rb:15
Protocol::WebSocket::Extension::Compression::MINIMUM_WINDOW_BITS = T.let(T.unsafe(nil), Integer)

# pkg:gem/protocol-websocket#lib/protocol/websocket/extension/compression/constants.rb:12
Protocol::WebSocket::Extension::Compression::NAME = T.let(T.unsafe(nil), String)

# Manages WebSocket extensions negotiated during the handshake.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/extensions.rb:13
module Protocol::WebSocket::Extensions
  class << self
    # Parse a list of extension header values into name and argument pairs.
    # @parameter headers [Array(String)] The raw extension header values.
    # @yields {|name, arguments| ...} Each parsed extension.
    # 	@parameter name [String] The name of the extension.
    # 	@parameter arguments [Array] The key-value argument pairs.
    #
    # pkg:gem/protocol-websocket#lib/protocol/websocket/extensions.rb:19
    def parse(headers); end
  end
end

# Manages extensions on the client side, offering and accepting server responses.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/extensions.rb:34
class Protocol::WebSocket::Extensions::Client
  # Initialize a new client extension manager.
  # @parameter extensions [Array] The list of extensions to offer, each as `[klass, options]`.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/extensions.rb:45
  def initialize(extensions = T.unsafe(nil)); end

  # Accept server extension responses and record the negotiated extensions.
  # @parameter headers [Array(String)] The `Sec-WebSocket-Extensions` response header values.
  # @returns [Array] The accepted extensions as `[klass, options]` pairs.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/extensions.rb:77
  def accept(headers); end

  # @attribute [Array] The extensions accepted after negotiation.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/extensions.rb:53
  def accepted; end

  # Apply all accepted extensions to the given connection as a client.
  # @parameter connection [Connection] The WebSocket connection to configure.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/extensions.rb:96
  def apply(connection); end

  # @attribute [Array] The list of extensions to offer.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/extensions.rb:51
  def extensions; end

  # Build a lookup table of extensions keyed by their name.
  # @returns [Hash] A hash mapping extension names to their `[klass, options]` pairs.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/extensions.rb:57
  def named; end

  # Yield extension offer headers for each registered extension.
  # @yields {|header| ...} Each offer header string.
  # 	@parameter header [Array(String)] The extension offer header tokens.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/extensions.rb:66
  def offer; end

  class << self
    # Create a default client with permessage-deflate compression enabled.
    # @returns [Client] A new client with the default compression extension.
    #
    # pkg:gem/protocol-websocket#lib/protocol/websocket/extensions.rb:37
    def default; end
  end
end

# Manages extensions on the server side, negotiating client offers and applying the agreed extensions.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/extensions.rb:104
class Protocol::WebSocket::Extensions::Server
  # Initialize a new server extension manager.
  # @parameter extensions [Array] The list of supported extensions, each as `[klass, options]`.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/extensions.rb:115
  def initialize(extensions); end

  # Negotiate client extension offers and yield accepted response headers.
  # @parameter headers [Array(String)] The `Sec-WebSocket-Extensions` request header values.
  # @yields {|header| ...} Each accepted extension header to include in the response.
  # 	@parameter header [Array(String)] The negotiated extension header tokens.
  # @returns [Array] The accepted extensions as `[klass, options]` pairs.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/extensions.rb:138
  def accept(headers); end

  # @attribute [Array] The extensions accepted after negotiation.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/extensions.rb:123
  def accepted; end

  # Apply all accepted extensions to the given connection as a server.
  # @parameter connection [Connection] The WebSocket connection to configure.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/extensions.rb:164
  def apply(connection); end

  # @attribute [Array] The list of supported extensions.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/extensions.rb:121
  def extensions; end

  # Build a lookup table of extensions keyed by their name.
  # @returns [Hash] A hash mapping extension names to their `[klass, options]` pairs.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/extensions.rb:127
  def named; end

  class << self
    # Create a default server with permessage-deflate compression enabled.
    # @returns [Server] A new server with the default compression extension.
    #
    # pkg:gem/protocol-websocket#lib/protocol/websocket/extensions.rb:107
    def default; end
  end
end

# HTTP/2 frame type mapping as defined by the spec.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/framer.rb:19
Protocol::WebSocket::FRAMES = T.let(T.unsafe(nil), Hash)

# Represents a single WebSocket frame as defined by RFC 6455.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/frame.rb:15
class Protocol::WebSocket::Frame
  include ::Comparable

  # @parameter mask [Boolean | String] An optional 4-byte string which is used to mask the payload.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/frame.rb:26
  def initialize(finished = T.unsafe(nil), payload = T.unsafe(nil), flags: T.unsafe(nil), opcode: T.unsafe(nil), mask: T.unsafe(nil)); end

  # Compare this frame to another frame by their array representation.
  # @parameter other [Frame] The frame to compare against.
  # @returns [Integer] A comparison result (-1, 0, or 1).
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/frame.rb:48
  def <=>(other); end

  # Apply this frame to the connection by dispatching it to the appropriate handler.
  # @parameter connection [Connection] The WebSocket connection to receive this frame.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/frame.rb:167
  def apply(connection); end

  # Check whether this frame is a continuation fragment (FIN bit not set).
  # @returns [Boolean] `true` if the FIN bit is not set.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/frame.rb:77
  def continued?; end

  # Check whether this is a control frame (opcode has bit 3 set).
  # @returns [Boolean] `true` if this is a control frame.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/frame.rb:60
  def control?; end

  # @returns [Boolean] if the frame contains data.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/frame.rb:65
  def data?; end

  # The generic frame header uses the following binary representation:
  #
  #  0                   1                   2                   3
  #  0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
  # +-+-+-+-+-------+-+-------------+-------------------------------+
  # |F|R|R|R| opcode|M| Payload len |    Extended payload length    |
  # |I|S|S|S|  (4)  |A|     (7)     |             (16/64)           |
  # |N|V|V|V|       |S|             |   (if payload len==126/127)   |
  # +-+-+-+-+-------+-+-------------+ - - - - - - - - - - - - - - - +
  # + - - - - - - - - - - - - - - - +-------------------------------+
  # +-------------------------------+-------------------------------+
  # +-------------------------------- - - - - - - - - - - - - - - - +
  # + - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
  # +---------------------------------------------------------------+
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/frame.rb:102
  def finished; end

  # The generic frame header uses the following binary representation:
  #
  #  0                   1                   2                   3
  #  0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
  # +-+-+-+-+-------+-+-------------+-------------------------------+
  # |F|R|R|R| opcode|M| Payload len |    Extended payload length    |
  # |I|S|S|S|  (4)  |A|     (7)     |             (16/64)           |
  # |N|V|V|V|       |S|             |   (if payload len==126/127)   |
  # +-+-+-+-+-------+-+-------------+ - - - - - - - - - - - - - - - +
  # + - - - - - - - - - - - - - - - +-------------------------------+
  # +-------------------------------+-------------------------------+
  # +-------------------------------- - - - - - - - - - - - - - - - +
  # + - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
  # +---------------------------------------------------------------+
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/frame.rb:102
  def finished=(_arg0); end

  # Check whether this is the final frame in a message.
  # @returns [Boolean] `true` if the FIN bit is set.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/frame.rb:71
  def finished?; end

  # Check whether the specified RSV flag bit is set on this frame.
  # @parameter value [Integer] The flag bitmask to test (e.g. `RSV1`).
  # @returns [Boolean] `true` if the flag bit is set.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/frame.rb:41
  def flag?(value); end

  # pkg:gem/protocol-websocket#lib/protocol/websocket/frame.rb:103
  def flags; end

  # pkg:gem/protocol-websocket#lib/protocol/websocket/frame.rb:103
  def flags=(_arg0); end

  # The byte length of the payload.
  # @returns [Integer | nil]
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/frame.rb:110
  def length; end

  # pkg:gem/protocol-websocket#lib/protocol/websocket/frame.rb:105
  def mask; end

  # pkg:gem/protocol-websocket#lib/protocol/websocket/frame.rb:105
  def mask=(_arg0); end

  # pkg:gem/protocol-websocket#lib/protocol/websocket/frame.rb:104
  def opcode; end

  # pkg:gem/protocol-websocket#lib/protocol/websocket/frame.rb:104
  def opcode=(_arg0); end

  # Pack the given data into this frame's payload, applying masking if configured.
  # @parameter data [String] The payload data to pack.
  # @returns [Frame] Returns `self`.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/frame.rb:141
  def pack(data = T.unsafe(nil)); end

  # pkg:gem/protocol-websocket#lib/protocol/websocket/frame.rb:106
  def payload; end

  # pkg:gem/protocol-websocket#lib/protocol/websocket/frame.rb:106
  def payload=(_arg0); end

  # Convert this frame to an array of its fields for comparison or inspection.
  # @returns [Array] An array of `[finished, flags, opcode, mask, payload]`.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/frame.rb:54
  def to_ary; end

  # Unpack the raw payload, removing masking if present.
  # @returns [String] The unmasked payload data.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/frame.rb:157
  def unpack; end

  private

  # pkg:gem/protocol-websocket#lib/protocol/websocket/frame.rb:115
  def mask_xor(data, mask); end
end

# pkg:gem/protocol-websocket#lib/protocol/websocket/frame.rb:23
Protocol::WebSocket::Frame::OPCODE = T.let(T.unsafe(nil), Integer)

# pkg:gem/protocol-websocket#lib/protocol/websocket/frame.rb:21
Protocol::WebSocket::Frame::RESERVED = T.let(T.unsafe(nil), Integer)

# pkg:gem/protocol-websocket#lib/protocol/websocket/frame.rb:18
Protocol::WebSocket::Frame::RSV1 = T.let(T.unsafe(nil), Integer)

# pkg:gem/protocol-websocket#lib/protocol/websocket/frame.rb:19
Protocol::WebSocket::Frame::RSV2 = T.let(T.unsafe(nil), Integer)

# pkg:gem/protocol-websocket#lib/protocol/websocket/frame.rb:20
Protocol::WebSocket::Frame::RSV3 = T.let(T.unsafe(nil), Integer)

# When the frame payload does not match expectations.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/error.rb:62
class Protocol::WebSocket::FrameSizeError < ::Protocol::WebSocket::ProtocolError; end

# Wraps an underlying {Async::IO::Stream} for reading and writing binary data into structured frames.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/framer.rb:32
class Protocol::WebSocket::Framer
  # Initialize a new framer wrapping the given stream.
  # @parameter stream [IO] The underlying stream to read from and write to.
  # @parameter frames [Hash] A mapping of opcodes to frame classes.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/framer.rb:36
  def initialize(stream, frames = T.unsafe(nil)); end

  # Close the underlying stream.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/framer.rb:42
  def close; end

  # Flush the underlying stream.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/framer.rb:47
  def flush; end

  # Read a frame from the underlying stream.
  # @returns [Frame] the frame read from the stream.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/framer.rb:53
  def read_frame(maximum_frame_size = T.unsafe(nil)); end

  # Write a frame to the underlying stream.
  # @parameter frame [Frame] The frame to serialize and write.
  # @raises [ProtocolError] If the frame has an invalid mask.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/framer.rb:123
  def write_frame(frame); end
end

# @namespace
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/headers.rb:12
module Protocol::WebSocket::Headers; end

# Provides utilities for generating and verifying the WebSocket handshake nonce.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/headers.rb:28
module Protocol::WebSocket::Headers::Nounce
  class << self
    # Valid for the `SEC_WEBSOCKET_ACCEPT` header.
    #
    # pkg:gem/protocol-websocket#lib/protocol/websocket/headers.rb:37
    def accept_digest(key); end

    # Valid for the `SEC_WEBSOCKET_KEY` header.
    #
    # pkg:gem/protocol-websocket#lib/protocol/websocket/headers.rb:32
    def generate_key; end
  end
end

# pkg:gem/protocol-websocket#lib/protocol/websocket/headers.rb:29
Protocol::WebSocket::Headers::Nounce::GUID = T.let(T.unsafe(nil), String)

# The protocol string used for the `upgrade:` header (HTTP/1) and `:protocol` pseudo-header (HTTP/2).
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/headers.rb:14
Protocol::WebSocket::Headers::PROTOCOL = T.let(T.unsafe(nil), String)

# pkg:gem/protocol-websocket#lib/protocol/websocket/headers.rb:23
Protocol::WebSocket::Headers::SEC_WEBSOCKET_ACCEPT = T.let(T.unsafe(nil), String)

# pkg:gem/protocol-websocket#lib/protocol/websocket/headers.rb:25
Protocol::WebSocket::Headers::SEC_WEBSOCKET_EXTENSIONS = T.let(T.unsafe(nil), String)

# pkg:gem/protocol-websocket#lib/protocol/websocket/headers.rb:22
Protocol::WebSocket::Headers::SEC_WEBSOCKET_KEY = T.let(T.unsafe(nil), String)

# The WebSocket protocol header, used for application level protocol negotiation.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/headers.rb:17
Protocol::WebSocket::Headers::SEC_WEBSOCKET_PROTOCOL = T.let(T.unsafe(nil), String)

# The WebSocket version header. Used for negotiating binary protocol version.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/headers.rb:20
Protocol::WebSocket::Headers::SEC_WEBSOCKET_VERSION = T.let(T.unsafe(nil), String)

# The maximum allowed frame size in bytes.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/framer.rb:29
Protocol::WebSocket::MAXIMUM_ALLOWED_FRAME_SIZE = T.let(T.unsafe(nil), Integer)

# Represents a message that can be sent or received over a WebSocket connection.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/message.rb:12
class Protocol::WebSocket::Message
  # Create a new message from a buffer.
  # @attribute buffer [String] The message buffer.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/message.rb:15
  def initialize(buffer = T.unsafe(nil)); end

  # Compare this message to another message or buffer.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/message.rb:28
  def ==(other); end

  # @attribute [String] The message buffer.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/message.rb:20
  def buffer; end

  # The encoding of the message buffer.
  # @returns [Encoding]
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/message.rb:39
  def encoding; end

  # Parse the message buffer using the given coder. Defaults to JSON.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/message.rb:51
  def parse(coder = T.unsafe(nil)); end

  # Send this message as a text frame over the given connection.
  # @parameter connection [Connection] The WebSocket connection to send through.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/message.rb:62
  def send(connection, **options); end

  # @returns [Integer] The size of the message buffer.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/message.rb:23
  def size; end

  # Convert the message buffer to a hash using the given coder. Defaults to JSON.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/message.rb:56
  def to_h(*, **, &); end

  # A message is implicitly convertible to it's buffer.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/message.rb:33
  def to_str; end

  class << self
    # Generate a message from a value using the given coder.
    # @property value [Object] The value to encode.
    # @property coder [Coder] The coder to use. Defaults to JSON.
    #
    # pkg:gem/protocol-websocket#lib/protocol/websocket/message.rb:46
    def generate(value, coder = T.unsafe(nil)); end
  end
end

# Represents a ping frame that is sent or received by a WebSocket connection.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/ping_frame.rb:12
class Protocol::WebSocket::PingFrame < ::Protocol::WebSocket::Frame
  # Apply this frame to the specified connection.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/ping_frame.rb:22
  def apply(connection); end

  # Generate a suitable reply.
  # @returns [PongFrame]
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/ping_frame.rb:17
  def reply(**options); end
end

# pkg:gem/protocol-websocket#lib/protocol/websocket/ping_frame.rb:13
Protocol::WebSocket::PingFrame::OPCODE = T.let(T.unsafe(nil), Integer)

# Represents a ping message that can be sent over a WebSocket connection.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/message.rb:81
class Protocol::WebSocket::PingMessage < ::Protocol::WebSocket::Message
  # Send this message as a ping frame over the given connection.
  # @parameter connection [Connection] The WebSocket connection to send through.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/message.rb:84
  def send(connection); end
end

# Represents a pong frame that is sent or received by a WebSocket connection.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/pong_frame.rb:11
class Protocol::WebSocket::PongFrame < ::Protocol::WebSocket::Frame
  # Apply this frame to the specified connection.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/pong_frame.rb:15
  def apply(connection); end
end

# pkg:gem/protocol-websocket#lib/protocol/websocket/pong_frame.rb:12
Protocol::WebSocket::PongFrame::OPCODE = T.let(T.unsafe(nil), Integer)

# Raised by stream or connection handlers, results in GOAWAY frame which signals termination of the current connection. You *cannot* recover from this exception, or any exceptions subclassed from it.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/error.rb:43
class Protocol::WebSocket::ProtocolError < ::Protocol::WebSocket::Error
  # Initialize a protocol error with an optional status code.
  # @parameter message [String] The error message.
  # @parameter code [Integer] The WebSocket status code associated with the error.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/error.rb:47
  def initialize(message, code = T.unsafe(nil)); end

  # @attribute [Integer] The status code associated with the error.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/error.rb:54
  def code; end
end

# Represents a text frame that is sent or received by a WebSocket connection.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/text_frame.rb:13
class Protocol::WebSocket::TextFrame < ::Protocol::WebSocket::Frame
  # Apply this frame to the specified connection.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/text_frame.rb:34
  def apply(connection); end

  # @returns [Boolean] if the frame contains data.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/text_frame.rb:17
  def data?; end

  # Decode the binary buffer into a suitable text message.
  # @parameter buffer [String] The binary data to unpack.
  #
  # pkg:gem/protocol-websocket#lib/protocol/websocket/text_frame.rb:23
  def read_message(buffer); end
end

# pkg:gem/protocol-websocket#lib/protocol/websocket/text_frame.rb:14
Protocol::WebSocket::TextFrame::OPCODE = T.let(T.unsafe(nil), Integer)

# Represents a text message that can be sent or received over a WebSocket connection.
#
# pkg:gem/protocol-websocket#lib/protocol/websocket/message.rb:68
class Protocol::WebSocket::TextMessage < ::Protocol::WebSocket::Message; end
